<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>第2层级的区域值</description>
   <name>area_valus</name>
   <tag></tag>
   <elementGuidId>d7edd462-5c0f-4ce9-9435-2841de8d4938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='drop-down-title7']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='drop-down-title7']/span</value>
   </webElementProperties>
</WebElementEntity>
