<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>区域</description>
   <name>area</name>
   <tag></tag>
   <elementGuidId>84f80b85-aaac-441b-b676-15794f025478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'right-area-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>right-area-input</value>
   </webElementProperties>
</WebElementEntity>
