<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>勾选记录</description>
   <name>check_wifi</name>
   <tag></tag>
   <elementGuidId>8c23da54-8f09-45f0-ad6e-8c8fb9277555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table_tbody&quot;]/tr[${index}]/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table_tbody&quot;]/tr[${index}]/td[2]/span</value>
   </webElementProperties>
</WebElementEntity>
