<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>编辑设置</description>
   <name>edit</name>
   <tag></tag>
   <elementGuidId>03f26331-ae9c-43fa-a356-1369c64b2364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sysoperate</value>
   </webElementProperties>
</WebElementEntity>
