<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>首级区域三角标</description>
   <name>shouji_icon</name>
   <tag></tag>
   <elementGuidId>79c6c438-c145-4779-80be-c847697a8480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>areaIco1</value>
   </webElementProperties>
</WebElementEntity>
