<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>wifi开关下拉选择</description>
   <name>wifi_on-off</name>
   <tag></tag>
   <elementGuidId>898201ab-af3e-4ed3-9c94-3885977fbe69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
   </webElementProperties>
</WebElementEntity>
