<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>点击登录按钮</description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>ee1777d6-d997-4410-a5e0-938c4b56218f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-button</value>
   </webElementProperties>
</WebElementEntity>
