<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>账户名</description>
   <name>username</name>
   <tag></tag>
   <elementGuidId>a108e71e-bfe3-4c03-a088-031586fa5e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-username</value>
   </webElementProperties>
</WebElementEntity>
