<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>区域名称</description>
   <name>area_name</name>
   <tag></tag>
   <elementGuidId>7c1fd8c3-96ac-4707-a3bf-10367b4ce31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>area-name</value>
   </webElementProperties>
</WebElementEntity>
