<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>区域管理菜单</description>
   <name>area</name>
   <tag></tag>
   <elementGuidId>0085df76-9d4c-41d7-9c53-e04899dc9cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>/setting</value>
   </webElementProperties>
</WebElementEntity>
