<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>删除的确认</description>
   <name>delete_queren</name>
   <tag></tag>
   <elementGuidId>4ce28d4a-334f-4e98-b259-0ef3b768dcff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='wrapper']//*[@class='footer']/button[2]</value>
   </webElementProperties>
</WebElementEntity>
