<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>确认</description>
   <name>queren</name>
   <tag></tag>
   <elementGuidId>67ade461-c79f-4d33-b601-aeced78a8e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div/div[3]/div/div/div[4]/div/div/div[2]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
