<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>搜索框</description>
   <name>search_area</name>
   <tag></tag>
   <elementGuidId>31ad0a36-7fea-4bab-8fe6-ca5add507e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='simulation-select']/input</value>
   </webElementProperties>
</WebElementEntity>
