<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>区域状态</description>
   <name>status</name>
   <tag></tag>
   <elementGuidId>464720d6-9ab1-4d52-89aa-578f4dded3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
   </webElementProperties>
</WebElementEntity>
