<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>修改区域名称</description>
   <name>update-areaname</name>
   <tag></tag>
   <elementGuidId>fea84808-538f-419c-a03d-952a74791634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>area-name</value>
   </webElementProperties>
</WebElementEntity>
