<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>确认</description>
   <name>update_queren</name>
   <tag></tag>
   <elementGuidId>8e481036-9fc7-4606-9ae2-d91daf062cda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='wrapper']/div/div[4]//*[@class='footer']/button[1]</value>
   </webElementProperties>
</WebElementEntity>
