<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>根据告警级别筛选</description>
   <name>alarm_level</name>
   <tag></tag>
   <elementGuidId>ec66511d-10ac-4178-9bd2-7a3eb09f603f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchItem0</value>
   </webElementProperties>
</WebElementEntity>
