<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>点击确认告警</description>
   <name>confirm_alarm</name>
   <tag></tag>
   <elementGuidId>34e61f39-85d3-4587-9cc6-5f393afaa6a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sysoperate</value>
   </webElementProperties>
</WebElementEntity>
