<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>模式切换</description>
   <name>model</name>
   <tag></tag>
   <elementGuidId>5c1a2c01-a933-43db-9853-0a56209ac425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monitorPattern1</value>
   </webElementProperties>
</WebElementEntity>
