<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>选择模式值</description>
   <name>model_valus</name>
   <tag></tag>
   <elementGuidId>e7e34c5a-188d-4fbb-bdea-8290dee88e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='regionsel']/li[3]</value>
   </webElementProperties>
</WebElementEntity>
