<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>点击告警记录菜单</description>
   <name>alarm_record</name>
   <tag></tag>
   <elementGuidId>f8b7f752-4f91-4ada-a7c2-6153ae1b2eaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>/record</value>
   </webElementProperties>
</WebElementEntity>
