<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>结束日期</description>
   <name>end-time</name>
   <tag></tag>
   <elementGuidId>1a1d7e7d-0a93-4804-a378-8814b94208d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end-time</value>
   </webElementProperties>
</WebElementEntity>
