<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>点击搜索按钮</description>
   <name>search_btn</name>
   <tag></tag>
   <elementGuidId>2fd740ea-692b-479f-ae12-79bea6309aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sysoperate</value>
   </webElementProperties>
</WebElementEntity>
