<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>点击开始时间</description>
   <name>start-time</name>
   <tag></tag>
   <elementGuidId>78f46bd8-a785-4c52-af44-df7f64df05a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start-time</value>
   </webElementProperties>
</WebElementEntity>
