<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>选择设备类型记录</description>
   <name>check_devicetype</name>
   <tag></tag>
   <elementGuidId>7a7f1a1c-1c46-45e0-b977-d5f44479b3b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='table_tbody']/tr[1]/td[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='table_tbody']/tr[1]/td[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
