<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>点击查询按钮</description>
   <name>click_search</name>
   <tag></tag>
   <elementGuidId>f3f724ae-6b73-47f8-aa35-1f1cc77e54d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='equipSearch']/i</value>
   </webElementProperties>
</WebElementEntity>
