<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>删除的确认</description>
   <name>delete_queren</name>
   <tag></tag>
   <elementGuidId>f3cb918b-58cd-4894-9a19-54aec562d7de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='wrapper']//*[@class='footer']/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='wrapper']//*[@class='footer']/button[2]</value>
   </webElementProperties>
</WebElementEntity>
