<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>添加操作</description>
   <name>new</name>
   <tag></tag>
   <elementGuidId>56eb035b-79d7-4587-802d-d247da1bbb15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class = 'iconfont icon-biaodan_tianjia']</value>
   </webElementProperties>
</WebElementEntity>
