<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>确认</description>
   <name>queren</name>
   <tag></tag>
   <elementGuidId>ed77837e-3eb8-4848-9303-b46cc244ecd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'lights-confirm-button']</value>
   </webElementProperties>
</WebElementEntity>
