<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>备注</description>
   <name>remark</name>
   <tag></tag>
   <elementGuidId>f5f86204-f42e-474b-91d8-555e549d84df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='remarks']/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='remarks']/textarea</value>
   </webElementProperties>
</WebElementEntity>
