<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>确认</description>
   <name>update_queren</name>
   <tag></tag>
   <elementGuidId>8a124607-6eb7-4296-902d-9f9ef7d8f890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lights-confirm-button</value>
   </webElementProperties>
</WebElementEntity>
