<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>设备序列号</description>
   <name>device_no</name>
   <tag></tag>
   <elementGuidId>9f31535a-13db-4b91-bfeb-435f0acb60ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[2]/div/div/div[1]/p[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[2]/div/div/div[1]/p[2][count(. | //input[@placeholder = '设备序列号' and @onkeyup = concat('this.value=this.value.replace(/[^\w-]/g,' , &quot;'&quot; , '' , &quot;'&quot; , ');')]) = count(//input[@placeholder = '设备序列号' and @onkeyup = concat('this.value=this.value.replace(/[^\w-]/g,' , &quot;'&quot; , '' , &quot;'&quot; , ');')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='content']/p[2]/input</value>
   </webElementProperties>
</WebElementEntity>
