<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>选择设备类型</description>
   <name>select_devicetype</name>
   <tag></tag>
   <elementGuidId>3f9239f9-c8a6-4b29-a449-9882fbe25d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='option-content']/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='option-content']/ul/li[1]</value>
   </webElementProperties>
</WebElementEntity>
