<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>点击首级三角标</description>
   <name>shouji_open</name>
   <tag></tag>
   <elementGuidId>2adf2d1f-bcc2-4799-87e1-4fc028c497f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='tree']/ul[1]/li[1]/div/i[1]</value>
   </webElementProperties>
</WebElementEntity>
