<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>修改设备名称</description>
   <name>update-devicename</name>
   <tag></tag>
   <elementGuidId>2e3808b0-d6d8-4688-b7a3-5dba45e4b369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='content']/p[1]/input</value>
   </webElementProperties>
</WebElementEntity>
