<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>编辑确认</description>
   <name>update_queren</name>
   <tag></tag>
   <elementGuidId>76b93132-b5b9-4f1c-a201-225c59e7a67d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[2]/div/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
